################################################################################
#
# libulfius
# https://github.com/babelouest/ulfius
#
################################################################################

LIBULFIUS_VERSION = 2.7.15
LIBULFIUS_SITE = $(call github,babelouest,ulfius,v$(LIBULFIUS_VERSION))
LIBULFIUS_LICENSE = GPL-2.1
LIBULFIUS_LICENSE_FILES = LICENSE
LIBULFIUS_INSTALL_STAGING = YES
LIBULFIUS_CONF_OPTS = \
	-DBUILD_STATIC=OFF \
	-DBUILD_ULFIUS_TESTING=OFF \
	-DBUILD_ULFIUS_DOCUMENTATION=OFF \
	-DINSTALL_HEADER=ON \
	-DCMAKE_BUILD_TYPE=Release
LIBULFIUS_DEPENDENCIES = \
	libmicrohttpd \
	liborcania

ifeq ($(BR2_PACKAGE_LIBULFIUS_JANSSON),y)
LIBULFIUS_DEPENDENCIES += jansson
LIBULFIUS_CONF_OPTS += -DWITH_JANSSON=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_JANSSON=OFF
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_CURL),y)
LIBULFIUS_DEPENDENCIES += libcurl
LIBULFIUS_CONF_OPTS += -DWITH_CURL=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_CURL=OFF
endif

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBULFIUS_DEPENDENCIES += openssl
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_GNUTLS),y)
LIBULFIUS_DEPENDENCIES += gnutls
LIBULFIUS_CONF_OPTS += -DWITH_GNUTLS=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_GNUTLS=OFF
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_WEBSOCKET),y)
LIBULFIUS_DEPENDENCIES += zlib libwebsockets
LIBULFIUS_CONF_OPTS += -DWITH_WEBSOCKET=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_WEBSOCKET=OFF
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_JOURNALD),y)
LIBULFIUS_DEPENDENCIES += systemd
LIBULFIUS_CONF_OPTS += -DWITH_JOURNALD=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_JOURNALD=OFF
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_YDER),y)
LIBULFIUS_DEPENDENCIES += libyder
LIBULFIUS_CONF_OPTS += -DWITH_YDER=ON
else
LIBULFIUS_CONF_OPTS += -DWITH_YDER=OFF
endif

ifeq ($(BR2_PACKAGE_LIBULFIUS_UWSC),y)
LIBULFIUS_CONF_OPTS += -DBUILD_UWSC=ON
else
LIBULFIUS_CONF_OPTS += -DBUILD_UWSC=OFF
endif

$(eval $(cmake-package))
