#!/bin/sh
#
# Starts the meshtasticd daemon.
# Inspired by:
# https://github.com/buildroot/buildroot/blob/master/package/docker-engine/S60dockerd
#

NAME=meshtasticd
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid

MESHTATICD_ARGS=""

start() {
	printf "Starting $NAME: "
	# Meshtasticd logs only to stdout/stderr, which is lost with
	# --background. The wrapper script runs the given command
	# (after "--", including meshtasticd) and forwards stdout/stderr
	# to syslog.
	# shellcheck disable=SC2086 # we need word splitting for MESHTASTICD_ARGS
	start-stop-daemon --start --background --pidfile "$PIDFILE" \
		--exec /usr/libexec/meshtasticd-syslog-wrapper.sh \
		-- "$DAEMON" $MESHTATICD_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
	rm -f $PIDFILE
}
restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
