#!/bin/sh
#
# Starts the meshtasticd daemon.
#

NAME=meshtasticd
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid

start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON && echo "OK" || echo "Failed"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
	rm -f $PIDFILE
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
