#!/bin/sh
#
# Starts the meshtasticd daemon.
#

NAME=meshtasticd
DAEMON=/usr/sbin/$NAME
PIDFILE=/var/run/$NAME.pid

start() {
	printf "Starting $NAME: "
	start-stop-daemon -S -q -p $PIDFILE --exec $DAEMON && echo "OK" || echo "Failed"
}
stop() {
	printf "Stopping $NAME: "
	start-stop-daemon -K -q -p $PIDFILE && echo "OK" || echo "Failed"
	rm -f $PIDFILE
}
status() {
	if [ -f "$PIDFILE" ]; then
		if ps -p $(cat $PIDFILE) > /dev/null 2>&1; then
			echo "$NAME is running (PID: $(cat $PIDFILE))"
		else
			echo "$NAME is not running, but PID file exists"
		fi
	else
		echo "$NAME is not running"
	fi
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
esac

exit $?
